### ISSUE TITLE
Test save / initial save persists through new projects

### ISSUE THREAD

**Issue by moehr-moehr** [ConConner/LAMP#34]
![image](https://user-images.githubusercontent.com/114267512/232057938-37485e94-bd0f-44ae-89bd-829f101a9076.png)

Should be:

![image](https://user-images.githubusercontent.com/114267512/232058498-0ae9a503-27d0-48e9-bdf8-04bf73e13a4a.png)

Deleted old ROM, deleted old project, copied in new ROM, made that the source, started new project, compiled to new ROM, and the test save data for the initial save modifier had overwritten my custom start save data which is incompatible

Note the starting energy in the first picture

Suggested fix: don't overwrite the starting save data unless a user is using the test room feature, and fix the testroom dialogue logic so that the program doesn't write new start data unless the box to do so is checked

Thank you!

**Comment by ConConner** [comment]
Until this gets fixed in a proper release, here is a quick fix one can do if they have a buildable source.

1. Open the file LAMP/Classes/M2 Data/Rom.cs
2. Go to the Compile() method
3. Go down to the `//Save` comment
4. Comment out `Globals.InitialSaveGame.WriteToROM(this)` or remove the line.

LAMP will now no longer replace the standard save file.

**Comment by ConConner** [comment]
Fixed in newest commit
