### ISSUE TITLE
Compiling LAMP project writes excess bank 3 data

### ISSUE THREAD

**Issue by moehr-moehr** [ConConner/LAMP#37]
Edit: Version:
![image](https://github.com/ConConner/LAMP/assets/114267512/e9ea5f71-627f-40f1-bd91-3d8dc2629884)

Assuming I've got the gist of how LAMP determines writing data when updating the screen enemy populations, I get the following byte changes in bank 3 when compiling the project to a new ROM.

OG bytes around E200:
![image](https://github.com/ConConner/LAMP/assets/114267512/0b1d1852-0a04-406d-8e79-88934d01e078)

After compiling to new ROM:
![image](https://github.com/ConConner/LAMP/assets/114267512/75116774-b31c-4f15-b889-54da88ea714d)

Since I am not actually changing any of the enemies, I can't figure out why it is writing all this data - unless I'm mistaken that saving the project and compiling to a new ROM without making any changes at all should be writing a new ROM that is identical to the old one.

**Comment by ConConner** [comment]
I could **not** replicate this doing the following:

1. Select an unmodified ROM as a base `(SHA1: 74A2FAD86B9A4C013149B1E214BC4600EFB1066D)`
2. Create a new project with it
3. Instantly compile the project again
4. Use HxD to compare the files

Original:
![](https://i.imgur.com/eXFbb5u.png)

Compiled:
![](https://i.imgur.com/p0sG9Om.png)

Its a near identical ROM. The only difference being that the LAMP compiled ROM has all the enemy data moved by one byte (This also means that every pointer in the enemy data is off by one byte), due to LAMP adding an extra `0xFF` as the first enemy set.

@moehr-moehr maybe I can replicate the issue if you upload the project files used.
